build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
filter:
  excluded_paths:
    - 'tests/*'
    - 'vendor/*'
checks:
  php: true
before_commands:
  - 'composer install --dev --prefer-source'
tools:
  external_code_coverage: true